// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "bootstrap.new.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://spclient.wg.spotify.com/bootstrap/v1/bootstrap
 *
 * @generated from protobuf message BootstrapResponse
 */
export interface BootstrapResponse {
    /**
     * @generated from protobuf field: UcsResponseWrapperV0 ucsResponseV0 = 2;
     */
    ucsResponseV0?: UcsResponseWrapperV0;
    /**
     * @generated from protobuf field: TrialsFacadeResponseWrapperV1 trialsFacadeResponseV1 = 3;
     */
    trialsFacadeResponseV1?: TrialsFacadeResponseWrapperV1;
}
/**
 * @generated from protobuf message UcsResponseWrapperV0
 */
export interface UcsResponseWrapperV0 {
    /**
     * @generated from protobuf field: UcsResponseWrapperSuccess success = 1;
     */
    success?: UcsResponseWrapperSuccess;
    /**
     * @generated from protobuf field: Error error = 2;
     */
    error?: Error;
}
/**
 * @generated from protobuf message UcsResponseWrapperSuccess
 */
export interface UcsResponseWrapperSuccess {
    /**
     * @generated from protobuf field: UcsResponseWrapper customization = 1;
     */
    customization?: UcsResponseWrapper;
}
/**
 * @generated from protobuf message UcsResponseWrapper
 */
export interface UcsResponseWrapper {
    /**
     * @generated from protobuf field: UcsResponse success = 1;
     */
    success?: UcsResponse;
    /**
     * @generated from protobuf field: Error error = 2;
     */
    error?: Error;
}
/**
 * @generated from protobuf message TrialsFacadeResponseWrapperV1
 */
export interface TrialsFacadeResponseWrapperV1 {
    /**
     * @generated from protobuf field: TrialsFacadeResponseWrapperSuccess success = 1;
     */
    success?: TrialsFacadeResponseWrapperSuccess;
    /**
     * @generated from protobuf field: Error error = 2;
     */
    error?: Error;
}
/**
 * @generated from protobuf message TrialsFacadeResponseWrapperSuccess
 */
export interface TrialsFacadeResponseWrapperSuccess {
    /**
     * @generated from protobuf field: int32 filed1 = 1;
     */
    filed1: number;
}
/**
 * @generated from protobuf message UcsResponse
 */
export interface UcsResponse {
    /**
     * @generated from protobuf field: ResolveResponse resolveSuccess = 1;
     */
    resolveSuccess?: ResolveResponse;
    /**
     * @generated from protobuf field: Error resolveError = 2;
     */
    resolveError?: Error;
    /**
     * @generated from protobuf field: AccountAttributesResponse accountAttributesSuccess = 3;
     */
    accountAttributesSuccess?: AccountAttributesResponse;
    /**
     * @generated from protobuf field: Error accountAttributesError = 4;
     */
    accountAttributesError?: Error;
    /**
     * @generated from protobuf field: int64 fetchTimeMillis = 5;
     */
    fetchTimeMillis: number;
}
/**
 * @generated from protobuf message ResolveResponse
 */
export interface ResolveResponse {
    /**
     * @generated from protobuf field: Configuration configuration = 1;
     */
    configuration?: Configuration;
}
/**
 * @generated from protobuf message Configuration
 */
export interface Configuration {
    /**
     * @generated from protobuf field: string configurationAssignmentId = 1;
     */
    configurationAssignmentId: string;
    /**
     * @generated from protobuf field: int64 fetchTimeMillis = 2;
     */
    fetchTimeMillis: number;
    /**
     * @generated from protobuf field: repeated AssignedValue assignedValues = 3;
     */
    assignedValues: AssignedValue[];
}
/**
 * @generated from protobuf message AssignedValue
 */
export interface AssignedValue {
    /**
     * @generated from protobuf field: PropertyId propertyId = 1;
     */
    propertyId?: PropertyId;
    /**
     * @generated from protobuf field: Metadata metadata = 2;
     */
    metadata?: Metadata;
    /**
     * @generated from protobuf field: BoolValue boolValue = 3;
     */
    boolValue?: BoolValue;
    /**
     * @generated from protobuf field: IntValue intValue = 4;
     */
    intValue?: IntValue;
    /**
     * @generated from protobuf field: EnumValue enumValue = 5;
     */
    enumValue?: EnumValue;
}
/**
 * @generated from protobuf message PropertyId
 */
export interface PropertyId {
    /**
     * @generated from protobuf field: string scope = 1;
     */
    scope: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
}
/**
 * @generated from protobuf message Metadata
 */
export interface Metadata {
    /**
     * @generated from protobuf field: int64 policyId = 1;
     */
    policyId: number;
    /**
     * @generated from protobuf field: string externalRealm = 2;
     */
    externalRealm: string;
    /**
     * @generated from protobuf field: int64 externalRealmId = 3;
     */
    externalRealmId: number;
}
/**
 * @generated from protobuf message BoolValue
 */
export interface BoolValue {
    /**
     * @generated from protobuf field: bool value = 1;
     */
    value: boolean;
}
/**
 * @generated from protobuf message EnumValue
 */
export interface EnumValue {
    /**
     * @generated from protobuf field: string value = 1;
     */
    value: string;
}
/**
 * @generated from protobuf message IntValue
 */
export interface IntValue {
    /**
     * @generated from protobuf field: int32 value = 1;
     */
    value: number;
}
/**
 * @generated from protobuf message AccountAttributesResponse
 */
export interface AccountAttributesResponse {
    /**
     * @generated from protobuf field: map<string, AccountAttribute> accountAttributes = 1;
     */
    accountAttributes: {
        [key: string]: AccountAttribute;
    };
}
/**
 * @generated from protobuf message AccountAttribute
 */
export interface AccountAttribute {
    /**
     * @generated from protobuf field: optional bool boolValue = 2;
     */
    boolValue?: boolean;
    /**
     * @generated from protobuf field: optional int64 longValue = 3;
     */
    longValue?: number;
    /**
     * @generated from protobuf field: optional string stringValue = 4;
     */
    stringValue?: string;
}
/**
 * @generated from protobuf message Error
 */
export interface Error {
    /**
     * @generated from protobuf field: int32 errorCode = 1;
     */
    errorCode: number;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: optional string logId = 3;
     */
    logId?: string;
}
declare class BootstrapResponse$Type extends MessageType<BootstrapResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message BootstrapResponse
 */
export declare const BootstrapResponse: BootstrapResponse$Type;
declare class UcsResponseWrapperV0$Type extends MessageType<UcsResponseWrapperV0> {
    constructor();
}
/**
 * @generated MessageType for protobuf message UcsResponseWrapperV0
 */
export declare const UcsResponseWrapperV0: UcsResponseWrapperV0$Type;
declare class UcsResponseWrapperSuccess$Type extends MessageType<UcsResponseWrapperSuccess> {
    constructor();
}
/**
 * @generated MessageType for protobuf message UcsResponseWrapperSuccess
 */
export declare const UcsResponseWrapperSuccess: UcsResponseWrapperSuccess$Type;
declare class UcsResponseWrapper$Type extends MessageType<UcsResponseWrapper> {
    constructor();
}
/**
 * @generated MessageType for protobuf message UcsResponseWrapper
 */
export declare const UcsResponseWrapper: UcsResponseWrapper$Type;
declare class TrialsFacadeResponseWrapperV1$Type extends MessageType<TrialsFacadeResponseWrapperV1> {
    constructor();
}
/**
 * @generated MessageType for protobuf message TrialsFacadeResponseWrapperV1
 */
export declare const TrialsFacadeResponseWrapperV1: TrialsFacadeResponseWrapperV1$Type;
declare class TrialsFacadeResponseWrapperSuccess$Type extends MessageType<TrialsFacadeResponseWrapperSuccess> {
    constructor();
}
/**
 * @generated MessageType for protobuf message TrialsFacadeResponseWrapperSuccess
 */
export declare const TrialsFacadeResponseWrapperSuccess: TrialsFacadeResponseWrapperSuccess$Type;
declare class UcsResponse$Type extends MessageType<UcsResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message UcsResponse
 */
export declare const UcsResponse: UcsResponse$Type;
declare class ResolveResponse$Type extends MessageType<ResolveResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message ResolveResponse
 */
export declare const ResolveResponse: ResolveResponse$Type;
declare class Configuration$Type extends MessageType<Configuration> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Configuration
 */
export declare const Configuration: Configuration$Type;
declare class AssignedValue$Type extends MessageType<AssignedValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message AssignedValue
 */
export declare const AssignedValue: AssignedValue$Type;
declare class PropertyId$Type extends MessageType<PropertyId> {
    constructor();
}
/**
 * @generated MessageType for protobuf message PropertyId
 */
export declare const PropertyId: PropertyId$Type;
declare class Metadata$Type extends MessageType<Metadata> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Metadata
 */
export declare const Metadata: Metadata$Type;
declare class BoolValue$Type extends MessageType<BoolValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message BoolValue
 */
export declare const BoolValue: BoolValue$Type;
declare class EnumValue$Type extends MessageType<EnumValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message EnumValue
 */
export declare const EnumValue: EnumValue$Type;
declare class IntValue$Type extends MessageType<IntValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message IntValue
 */
export declare const IntValue: IntValue$Type;
declare class AccountAttributesResponse$Type extends MessageType<AccountAttributesResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message AccountAttributesResponse
 */
export declare const AccountAttributesResponse: AccountAttributesResponse$Type;
declare class AccountAttribute$Type extends MessageType<AccountAttribute> {
    constructor();
}
/**
 * @generated MessageType for protobuf message AccountAttribute
 */
export declare const AccountAttribute: AccountAttribute$Type;
declare class Error$Type extends MessageType<Error> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Error
 */
export declare const Error: Error$Type;
export {};
