// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "ExtendedMetadata.proto" (package "com.spotify.extendedmetadata.proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Any } from "./google/protobuf/any";
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.BatchedEntityRequest
 */
export interface BatchedEntityRequest {
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.BatchedEntityRequestHeader header = 1;
     */
    header?: BatchedEntityRequestHeader;
    /**
     * @generated from protobuf field: repeated com.spotify.extendedmetadata.proto.EntityRequest request = 2;
     */
    request: EntityRequest[];
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.BatchedEntityRequestHeader
 */
export interface BatchedEntityRequestHeader {
    /**
     * @generated from protobuf field: string country = 1;
     */
    country: string;
    /**
     * @generated from protobuf field: string catalogue = 2;
     */
    catalogue: string;
    /**
     * @generated from protobuf field: bytes task_id = 3;
     */
    taskId: Uint8Array;
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.EntityRequest
 */
export interface EntityRequest {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: repeated com.spotify.extendedmetadata.proto.ExtensionQuery query = 2;
     */
    query: ExtensionQuery[];
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.ExtensionQuery
 */
export interface ExtensionQuery {
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.ExtensionKind kind = 1;
     */
    kind: ExtensionKind;
    /**
     * @generated from protobuf field: optional string etag = 2;
     */
    etag?: string;
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.BatchedExtensionResponse
 */
export interface BatchedExtensionResponse {
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.BatchedExtensionResponseHeader header = 1;
     */
    header?: BatchedExtensionResponseHeader;
    /**
     * @generated from protobuf field: repeated com.spotify.extendedmetadata.proto.EntityExtensionDataArray extended_metadata = 2;
     */
    extendedMetadata: EntityExtensionDataArray[];
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.BatchedExtensionResponseHeader
 */
export interface BatchedExtensionResponseHeader {
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.EntityExtensionDataArray
 */
export interface EntityExtensionDataArray {
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.EntityExtensionDataArrayHeader header = 1;
     */
    header?: EntityExtensionDataArrayHeader;
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.ExtensionKind kind = 2;
     */
    kind: ExtensionKind;
    /**
     * @generated from protobuf field: repeated com.spotify.extendedmetadata.proto.EntityExtensionData extension_data = 3;
     */
    extensionData: EntityExtensionData[];
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.EntityExtensionDataArrayHeader
 */
export interface EntityExtensionDataArrayHeader {
    /**
     * @generated from protobuf field: int32 provider_error_status = 1;
     */
    providerErrorStatus: number;
    /**
     * @generated from protobuf field: int64 cache_ttl_in_seconds = 2;
     */
    cacheTtlInSeconds: number;
    /**
     * @generated from protobuf field: int64 offline_ttl_in_seconds = 3;
     */
    offlineTtlInSeconds: number;
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.ExtensionType extension_type = 4;
     */
    extensionType: ExtensionType;
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.EntityExtensionData
 */
export interface EntityExtensionData {
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.EntityExtensionDataHeader header = 1;
     */
    header?: EntityExtensionDataHeader;
    /**
     * @generated from protobuf field: string entity_uri = 2;
     */
    entityUri: string;
    /**
     * Metadata object
     *
     * @generated from protobuf field: google.protobuf.Any extension_data = 3;
     */
    extensionData?: Any;
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.EntityExtensionDataHeader
 */
export interface EntityExtensionDataHeader {
    /**
     * @generated from protobuf field: int32 status_code = 1;
     */
    statusCode: number;
    /**
     * @generated from protobuf field: string etag = 2;
     */
    etag: string;
    /**
     * @generated from protobuf field: string locale = 3;
     */
    locale: string;
    /**
     * @generated from protobuf field: int64 cache_ttl_in_seconds = 4;
     */
    cacheTtlInSeconds: number;
    /**
     * @generated from protobuf field: int64 offline_ttl_in_seconds = 5;
     */
    offlineTtlInSeconds: number;
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.PlainListAssoc
 */
export interface PlainListAssoc {
    /**
     * @generated from protobuf field: repeated string entity_uri = 1;
     */
    entityUri: string[];
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.AssocHeader
 */
export interface AssocHeader {
}
/**
 * @generated from protobuf message com.spotify.extendedmetadata.proto.Assoc
 */
export interface Assoc {
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.AssocHeader header = 1;
     */
    header?: AssocHeader;
    /**
     * @generated from protobuf field: com.spotify.extendedmetadata.proto.PlainListAssoc plain_list = 2;
     */
    plainList?: PlainListAssoc;
}
/**
 * @generated from protobuf enum com.spotify.extendedmetadata.proto.ExtensionType
 */
export declare enum ExtensionType {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: GENERIC = 1;
     */
    GENERIC = 1,
    /**
     * @generated from protobuf enum value: ASSOC = 2;
     */
    ASSOC = 2
}
/**
 * @generated from protobuf enum com.spotify.extendedmetadata.proto.ExtensionKind
 */
export declare enum ExtensionKind {
    /**
     * @generated from protobuf enum value: UNKNOWN_EXTENSION = 0;
     */
    UNKNOWN_EXTENSION = 0,
    /**
     * @generated from protobuf enum value: CANVAZ = 1;
     */
    CANVAZ = 1,
    /**
     * @generated from protobuf enum value: STORYLINES = 2;
     */
    STORYLINES = 2,
    /**
     * @generated from protobuf enum value: PODCAST_TOPICS = 3;
     */
    PODCAST_TOPICS = 3,
    /**
     * @generated from protobuf enum value: PODCAST_SEGMENTS = 4;
     */
    PODCAST_SEGMENTS = 4,
    /**
     * @generated from protobuf enum value: AUDIO_FILES = 5;
     */
    AUDIO_FILES = 5,
    /**
     * @generated from protobuf enum value: TRACK_DESCRIPTOR = 6;
     */
    TRACK_DESCRIPTOR = 6,
    /**
     * @generated from protobuf enum value: PODCAST_COUNTER = 7;
     */
    PODCAST_COUNTER = 7,
    /**
     * @generated from protobuf enum value: ARTIST_V4 = 8;
     */
    ARTIST_V4 = 8,
    /**
     * @generated from protobuf enum value: ALBUM_V4 = 9;
     */
    ALBUM_V4 = 9,
    /**
     * @generated from protobuf enum value: TRACK_V4 = 10;
     */
    TRACK_V4 = 10,
    /**
     * @generated from protobuf enum value: SHOW_V4 = 11;
     */
    SHOW_V4 = 11,
    /**
     * @generated from protobuf enum value: EPISODE_V4 = 12;
     */
    EPISODE_V4 = 12,
    /**
     * @generated from protobuf enum value: PODCAST_HTML_DESCRIPTION = 13;
     */
    PODCAST_HTML_DESCRIPTION = 13,
    /**
     * @generated from protobuf enum value: PODCAST_QUOTES = 14;
     */
    PODCAST_QUOTES = 14,
    /**
     * @generated from protobuf enum value: USER_PROFILE = 15;
     */
    USER_PROFILE = 15,
    /**
     * @generated from protobuf enum value: CANVAS_V1 = 16;
     */
    CANVAS_V1 = 16,
    /**
     * @generated from protobuf enum value: SHOW_V4_BASE = 17;
     */
    SHOW_V4_BASE = 17,
    /**
     * @generated from protobuf enum value: SHOW_V4_EPISODES_ASSOC = 18;
     */
    SHOW_V4_EPISODES_ASSOC = 18,
    /**
     * @generated from protobuf enum value: TRACK_DESCRIPTOR_SIGNATURES = 19;
     */
    TRACK_DESCRIPTOR_SIGNATURES = 19,
    /**
     * @generated from protobuf enum value: PODCAST_AD_SEGMENTS = 20;
     */
    PODCAST_AD_SEGMENTS = 20,
    /**
     * @generated from protobuf enum value: EPISODE_TRANSCRIPTS = 21;
     */
    EPISODE_TRANSCRIPTS = 21,
    /**
     * @generated from protobuf enum value: PODCAST_SUBSCRIPTIONS = 22;
     */
    PODCAST_SUBSCRIPTIONS = 22,
    /**
     * @generated from protobuf enum value: EXTRACTED_COLOR = 23;
     */
    EXTRACTED_COLOR = 23,
    /**
     * @generated from protobuf enum value: PODCAST_VIRALITY = 24;
     */
    PODCAST_VIRALITY = 24,
    /**
     * @generated from protobuf enum value: IMAGE_SPARKLES_HACK = 25;
     */
    IMAGE_SPARKLES_HACK = 25,
    /**
     * @generated from protobuf enum value: PODCAST_POPULARITY_HACK = 26;
     */
    PODCAST_POPULARITY_HACK = 26,
    /**
     * @generated from protobuf enum value: AUTOMIX_MODE = 27;
     */
    AUTOMIX_MODE = 27,
    /**
     * @generated from protobuf enum value: CUEPOINTS = 28;
     */
    CUEPOINTS = 28,
    /**
     * @generated from protobuf enum value: PODCAST_POLL = 29;
     */
    PODCAST_POLL = 29,
    /**
     * @generated from protobuf enum value: EPISODE_ACCESS = 30;
     */
    EPISODE_ACCESS = 30,
    /**
     * @generated from protobuf enum value: SHOW_ACCESS = 31;
     */
    SHOW_ACCESS = 31,
    /**
     * @generated from protobuf enum value: PODCAST_QNA = 32;
     */
    PODCAST_QNA = 32,
    /**
     * @generated from protobuf enum value: CLIPS = 33;
     */
    CLIPS = 33,
    /**
     * @generated from protobuf enum value: SHOW_V5 = 34;
     */
    SHOW_V5 = 34,
    /**
     * @generated from protobuf enum value: EPISODE_V5 = 35;
     */
    EPISODE_V5 = 35,
    /**
     * @generated from protobuf enum value: PODCAST_CTA_CARDS = 36;
     */
    PODCAST_CTA_CARDS = 36,
    /**
     * @generated from protobuf enum value: PODCAST_RATING = 37;
     */
    PODCAST_RATING = 37,
    /**
     * @generated from protobuf enum value: DISPLAY_SEGMENTS = 38;
     */
    DISPLAY_SEGMENTS = 38,
    /**
     * @generated from protobuf enum value: GREENROOM = 39;
     */
    GREENROOM = 39,
    /**
     * @generated from protobuf enum value: USER_CREATED = 40;
     */
    USER_CREATED = 40,
    /**
     * @generated from protobuf enum value: SHOW_DESCRIPTION = 41;
     */
    SHOW_DESCRIPTION = 41,
    /**
     * @generated from protobuf enum value: SHOW_HTML_DESCRIPTION = 42;
     */
    SHOW_HTML_DESCRIPTION = 42,
    /**
     * @generated from protobuf enum value: SHOW_PLAYABILITY = 43;
     */
    SHOW_PLAYABILITY = 43,
    /**
     * @generated from protobuf enum value: EPISODE_DESCRIPTION = 44;
     */
    EPISODE_DESCRIPTION = 44,
    /**
     * @generated from protobuf enum value: EPISODE_HTML_DESCRIPTION = 45;
     */
    EPISODE_HTML_DESCRIPTION = 45,
    /**
     * @generated from protobuf enum value: EPISODE_PLAYABILITY = 46;
     */
    EPISODE_PLAYABILITY = 46,
    /**
     * @generated from protobuf enum value: SHOW_EPISODES_ASSOC = 47;
     */
    SHOW_EPISODES_ASSOC = 47,
    /**
     * @generated from protobuf enum value: CLIENT_CONFIG = 48;
     */
    CLIENT_CONFIG = 48,
    /**
     * @generated from protobuf enum value: PLAYLISTABILITY = 49;
     */
    PLAYLISTABILITY = 49,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_V5 = 50;
     */
    AUDIOBOOK_V5 = 50,
    /**
     * @generated from protobuf enum value: CHAPTER_V5 = 51;
     */
    CHAPTER_V5 = 51,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_SPECIFICS = 52;
     */
    AUDIOBOOK_SPECIFICS = 52,
    /**
     * @generated from protobuf enum value: EPISODE_RANKING = 53;
     */
    EPISODE_RANKING = 53,
    /**
     * @generated from protobuf enum value: HTML_DESCRIPTION = 54;
     */
    HTML_DESCRIPTION = 54,
    /**
     * @generated from protobuf enum value: CREATOR_CHANNEL = 55;
     */
    CREATOR_CHANNEL = 55,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_PROVIDERS = 56;
     */
    AUDIOBOOK_PROVIDERS = 56,
    /**
     * @generated from protobuf enum value: PLAY_TRAIT = 57;
     */
    PLAY_TRAIT = 57,
    /**
     * @generated from protobuf enum value: CONTENT_WARNING = 58;
     */
    CONTENT_WARNING = 58,
    /**
     * @generated from protobuf enum value: IMAGE_CUE = 59;
     */
    IMAGE_CUE = 59,
    /**
     * @generated from protobuf enum value: STREAM_COUNT = 60;
     */
    STREAM_COUNT = 60,
    /**
     * @generated from protobuf enum value: AUDIO_ATTRIBUTES = 61;
     */
    AUDIO_ATTRIBUTES = 61,
    /**
     * @generated from protobuf enum value: NAVIGABLE_TRAIT = 62;
     */
    NAVIGABLE_TRAIT = 62,
    /**
     * @generated from protobuf enum value: NEXT_BEST_EPISODE = 63;
     */
    NEXT_BEST_EPISODE = 63,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_PRICE = 64;
     */
    AUDIOBOOK_PRICE = 64,
    /**
     * @generated from protobuf enum value: EXPRESSIVE_PLAYLISTS = 65;
     */
    EXPRESSIVE_PLAYLISTS = 65,
    /**
     * @generated from protobuf enum value: DYNAMIC_SHOW_EPISODE = 66;
     */
    DYNAMIC_SHOW_EPISODE = 66,
    /**
     * @generated from protobuf enum value: LIVE = 67;
     */
    LIVE = 67,
    /**
     * @generated from protobuf enum value: SKIP_PLAYED = 68;
     */
    SKIP_PLAYED = 68,
    /**
     * @generated from protobuf enum value: AD_BREAK_FREE_PODCASTS = 69;
     */
    AD_BREAK_FREE_PODCASTS = 69,
    /**
     * @generated from protobuf enum value: ASSOCIATIONS = 70;
     */
    ASSOCIATIONS = 70,
    /**
     * @generated from protobuf enum value: PLAYLIST_EVALUATION = 71;
     */
    PLAYLIST_EVALUATION = 71,
    /**
     * @generated from protobuf enum value: CACHE_INVALIDATIONS = 72;
     */
    CACHE_INVALIDATIONS = 72,
    /**
     * @generated from protobuf enum value: LIVESTREAM_ENTITY = 73;
     */
    LIVESTREAM_ENTITY = 73,
    /**
     * @generated from protobuf enum value: SINGLE_TAP_REACTIONS = 74;
     */
    SINGLE_TAP_REACTIONS = 74,
    /**
     * @generated from protobuf enum value: USER_COMMENTS = 75;
     */
    USER_COMMENTS = 75,
    /**
     * @generated from protobuf enum value: CLIENT_RESTRICTIONS = 76;
     */
    CLIENT_RESTRICTIONS = 76,
    /**
     * @generated from protobuf enum value: PODCAST_GUEST = 77;
     */
    PODCAST_GUEST = 77,
    /**
     * @generated from protobuf enum value: PLAYABILITY = 78;
     */
    PLAYABILITY = 78,
    /**
     * @generated from protobuf enum value: COVER_IMAGE = 79;
     */
    COVER_IMAGE = 79,
    /**
     * @generated from protobuf enum value: SHARE_TRAIT = 80;
     */
    SHARE_TRAIT = 80,
    /**
     * @generated from protobuf enum value: INSTANCE_SHARING = 81;
     */
    INSTANCE_SHARING = 81,
    /**
     * @generated from protobuf enum value: ARTIST_TOUR = 82;
     */
    ARTIST_TOUR = 82,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_GENRE = 83;
     */
    AUDIOBOOK_GENRE = 83,
    /**
     * @generated from protobuf enum value: CONCEPT = 84;
     */
    CONCEPT = 84,
    /**
     * @generated from protobuf enum value: ORIGINAL_VIDEO = 85;
     */
    ORIGINAL_VIDEO = 85,
    /**
     * @generated from protobuf enum value: SMART_SHUFFLE = 86;
     */
    SMART_SHUFFLE = 86,
    /**
     * @generated from protobuf enum value: LIVE_EVENTS = 87;
     */
    LIVE_EVENTS = 87,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_RELATIONS = 88;
     */
    AUDIOBOOK_RELATIONS = 88,
    /**
     * @generated from protobuf enum value: HOME_POC_BASECARD = 89;
     */
    HOME_POC_BASECARD = 89,
    /**
     * @generated from protobuf enum value: AUDIOBOOK_SUPPLEMENTS = 90;
     */
    AUDIOBOOK_SUPPLEMENTS = 90,
    /**
     * @generated from protobuf enum value: PAID_PODCAST_BANNER = 91;
     */
    PAID_PODCAST_BANNER = 91,
    /**
     * @generated from protobuf enum value: FEWER_ADS = 92;
     */
    FEWER_ADS = 92,
    /**
     * @generated from protobuf enum value: WATCH_FEED_SHOW_EXPLORER = 93;
     */
    WATCH_FEED_SHOW_EXPLORER = 93,
    /**
     * @generated from protobuf enum value: TRACK_EXTRA_DESCRIPTORS = 94;
     */
    TRACK_EXTRA_DESCRIPTORS = 94,
    /**
     * @generated from protobuf enum value: TRACK_EXTRA_AUDIO_ATTRIBUTES = 95;
     */
    TRACK_EXTRA_AUDIO_ATTRIBUTES = 95,
    /**
     * @generated from protobuf enum value: TRACK_EXTENDED_CREDITS = 96;
     */
    TRACK_EXTENDED_CREDITS = 96,
    /**
     * @generated from protobuf enum value: SIMPLE_TRAIT = 97;
     */
    SIMPLE_TRAIT = 97,
    /**
     * @generated from protobuf enum value: AUDIO_ASSOCIATIONS = 98;
     */
    AUDIO_ASSOCIATIONS = 98,
    /**
     * @generated from protobuf enum value: VIDEO_ASSOCIATIONS = 99;
     */
    VIDEO_ASSOCIATIONS = 99,
    /**
     * @generated from protobuf enum value: PLAYLIST_TUNER = 100;
     */
    PLAYLIST_TUNER = 100,
    /**
     * @generated from protobuf enum value: ARTIST_VIDEOS_ENTRYPOINT = 101;
     */
    ARTIST_VIDEOS_ENTRYPOINT = 101,
    /**
     * @generated from protobuf enum value: PRERELEASE = 102;
     */
    PRERELEASE = 102,
    /**
     * @generated from protobuf enum value: CONTENT_ALTERNATIVES = 103;
     */
    CONTENT_ALTERNATIVES = 103,
    /**
     * @generated from protobuf enum value: SNAPSHOT_SHARING = 105;
     */
    SNAPSHOT_SHARING = 105
}
declare class BatchedEntityRequest$Type extends MessageType<BatchedEntityRequest> {
    constructor();
    create(value?: PartialMessage<BatchedEntityRequest>): BatchedEntityRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchedEntityRequest): BatchedEntityRequest;
    internalBinaryWrite(message: BatchedEntityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.BatchedEntityRequest
 */
export declare const BatchedEntityRequest: BatchedEntityRequest$Type;
declare class BatchedEntityRequestHeader$Type extends MessageType<BatchedEntityRequestHeader> {
    constructor();
    create(value?: PartialMessage<BatchedEntityRequestHeader>): BatchedEntityRequestHeader;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchedEntityRequestHeader): BatchedEntityRequestHeader;
    internalBinaryWrite(message: BatchedEntityRequestHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.BatchedEntityRequestHeader
 */
export declare const BatchedEntityRequestHeader: BatchedEntityRequestHeader$Type;
declare class EntityRequest$Type extends MessageType<EntityRequest> {
    constructor();
    create(value?: PartialMessage<EntityRequest>): EntityRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityRequest): EntityRequest;
    internalBinaryWrite(message: EntityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.EntityRequest
 */
export declare const EntityRequest: EntityRequest$Type;
declare class ExtensionQuery$Type extends MessageType<ExtensionQuery> {
    constructor();
    create(value?: PartialMessage<ExtensionQuery>): ExtensionQuery;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExtensionQuery): ExtensionQuery;
    internalBinaryWrite(message: ExtensionQuery, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.ExtensionQuery
 */
export declare const ExtensionQuery: ExtensionQuery$Type;
declare class BatchedExtensionResponse$Type extends MessageType<BatchedExtensionResponse> {
    constructor();
    create(value?: PartialMessage<BatchedExtensionResponse>): BatchedExtensionResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchedExtensionResponse): BatchedExtensionResponse;
    internalBinaryWrite(message: BatchedExtensionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.BatchedExtensionResponse
 */
export declare const BatchedExtensionResponse: BatchedExtensionResponse$Type;
declare class BatchedExtensionResponseHeader$Type extends MessageType<BatchedExtensionResponseHeader> {
    constructor();
    create(value?: PartialMessage<BatchedExtensionResponseHeader>): BatchedExtensionResponseHeader;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchedExtensionResponseHeader): BatchedExtensionResponseHeader;
    internalBinaryWrite(message: BatchedExtensionResponseHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.BatchedExtensionResponseHeader
 */
export declare const BatchedExtensionResponseHeader: BatchedExtensionResponseHeader$Type;
declare class EntityExtensionDataArray$Type extends MessageType<EntityExtensionDataArray> {
    constructor();
    create(value?: PartialMessage<EntityExtensionDataArray>): EntityExtensionDataArray;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityExtensionDataArray): EntityExtensionDataArray;
    internalBinaryWrite(message: EntityExtensionDataArray, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.EntityExtensionDataArray
 */
export declare const EntityExtensionDataArray: EntityExtensionDataArray$Type;
declare class EntityExtensionDataArrayHeader$Type extends MessageType<EntityExtensionDataArrayHeader> {
    constructor();
    create(value?: PartialMessage<EntityExtensionDataArrayHeader>): EntityExtensionDataArrayHeader;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityExtensionDataArrayHeader): EntityExtensionDataArrayHeader;
    internalBinaryWrite(message: EntityExtensionDataArrayHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.EntityExtensionDataArrayHeader
 */
export declare const EntityExtensionDataArrayHeader: EntityExtensionDataArrayHeader$Type;
declare class EntityExtensionData$Type extends MessageType<EntityExtensionData> {
    constructor();
    create(value?: PartialMessage<EntityExtensionData>): EntityExtensionData;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityExtensionData): EntityExtensionData;
    internalBinaryWrite(message: EntityExtensionData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.EntityExtensionData
 */
export declare const EntityExtensionData: EntityExtensionData$Type;
declare class EntityExtensionDataHeader$Type extends MessageType<EntityExtensionDataHeader> {
    constructor();
    create(value?: PartialMessage<EntityExtensionDataHeader>): EntityExtensionDataHeader;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityExtensionDataHeader): EntityExtensionDataHeader;
    internalBinaryWrite(message: EntityExtensionDataHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.EntityExtensionDataHeader
 */
export declare const EntityExtensionDataHeader: EntityExtensionDataHeader$Type;
declare class PlainListAssoc$Type extends MessageType<PlainListAssoc> {
    constructor();
    create(value?: PartialMessage<PlainListAssoc>): PlainListAssoc;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlainListAssoc): PlainListAssoc;
    internalBinaryWrite(message: PlainListAssoc, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.PlainListAssoc
 */
export declare const PlainListAssoc: PlainListAssoc$Type;
declare class AssocHeader$Type extends MessageType<AssocHeader> {
    constructor();
    create(value?: PartialMessage<AssocHeader>): AssocHeader;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AssocHeader): AssocHeader;
    internalBinaryWrite(message: AssocHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.AssocHeader
 */
export declare const AssocHeader: AssocHeader$Type;
declare class Assoc$Type extends MessageType<Assoc> {
    constructor();
    create(value?: PartialMessage<Assoc>): Assoc;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Assoc): Assoc;
    internalBinaryWrite(message: Assoc, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.extendedmetadata.proto.Assoc
 */
export declare const Assoc: Assoc$Type;
export {};
