// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "property_definition.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "property_definition.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDefinition$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.PropertyDefinition", [
            { no: 1, name: "id", kind: "message", T: () => PropertyDefinition_Identifier },
            { no: 4, name: "metadata", kind: "message", T: () => PropertyDefinition_Metadata },
            { no: 5, name: "bool_spec", kind: "message", oneof: "specification", T: () => PropertyDefinition_BoolSpec },
            { no: 6, name: "int_spec", kind: "message", oneof: "specification", T: () => PropertyDefinition_IntSpec },
            { no: 7, name: "enum_spec", kind: "message", oneof: "specification", T: () => PropertyDefinition_EnumSpec }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition
 */
export const PropertyDefinition = new PropertyDefinition$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDefinition_Identifier$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.PropertyDefinition.Identifier", [
            { no: 1, name: "scope", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.Identifier
 */
export const PropertyDefinition_Identifier = new PropertyDefinition_Identifier$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDefinition_Metadata$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.PropertyDefinition.Metadata", [
            { no: 1, name: "component_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.Metadata
 */
export const PropertyDefinition_Metadata = new PropertyDefinition_Metadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDefinition_BoolSpec$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.PropertyDefinition.BoolSpec", [
            { no: 1, name: "default", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.BoolSpec
 */
export const PropertyDefinition_BoolSpec = new PropertyDefinition_BoolSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDefinition_IntSpec$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.PropertyDefinition.IntSpec", [
            { no: 1, name: "default", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "lower", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "upper", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.IntSpec
 */
export const PropertyDefinition_IntSpec = new PropertyDefinition_IntSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDefinition_EnumSpec$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.PropertyDefinition.EnumSpec", [
            { no: 1, name: "default", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "values", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.EnumSpec
 */
export const PropertyDefinition_EnumSpec = new PropertyDefinition_EnumSpec$Type();
