// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "property_definition.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.PropertyDefinition
 */
export interface PropertyDefinition {
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.PropertyDefinition.Identifier id = 1;
     */
    id?: PropertyDefinition_Identifier;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.PropertyDefinition.Metadata metadata = 4;
     */
    metadata?: PropertyDefinition_Metadata;
    /**
     * @generated from protobuf oneof: specification
     */
    specification: {
        oneofKind: "boolSpec";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.PropertyDefinition.BoolSpec bool_spec = 5;
         */
        boolSpec: PropertyDefinition_BoolSpec;
    } | {
        oneofKind: "intSpec";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.PropertyDefinition.IntSpec int_spec = 6;
         */
        intSpec: PropertyDefinition_IntSpec;
    } | {
        oneofKind: "enumSpec";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.PropertyDefinition.EnumSpec enum_spec = 7;
         */
        enumSpec: PropertyDefinition_EnumSpec;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.Identifier
 */
export interface PropertyDefinition_Identifier {
    /**
     * @generated from protobuf field: string scope = 1;
     */
    scope: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.Metadata
 */
export interface PropertyDefinition_Metadata {
    /**
     * @generated from protobuf field: string component_id = 1;
     */
    componentId: string;
    /**
     * @generated from protobuf field: string description = 2;
     */
    description: string;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.BoolSpec
 */
export interface PropertyDefinition_BoolSpec {
    /**
     * @generated from protobuf field: bool default = 1;
     */
    default: boolean;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.IntSpec
 */
export interface PropertyDefinition_IntSpec {
    /**
     * @generated from protobuf field: int32 default = 1;
     */
    default: number;
    /**
     * @generated from protobuf field: int32 lower = 2;
     */
    lower: number;
    /**
     * @generated from protobuf field: int32 upper = 3;
     */
    upper: number;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.EnumSpec
 */
export interface PropertyDefinition_EnumSpec {
    /**
     * @generated from protobuf field: string default = 1;
     */
    default: string;
    /**
     * @generated from protobuf field: repeated string values = 2;
     */
    values: string[];
}
declare class PropertyDefinition$Type extends MessageType<PropertyDefinition> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition
 */
export declare const PropertyDefinition: PropertyDefinition$Type;
declare class PropertyDefinition_Identifier$Type extends MessageType<PropertyDefinition_Identifier> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.Identifier
 */
export declare const PropertyDefinition_Identifier: PropertyDefinition_Identifier$Type;
declare class PropertyDefinition_Metadata$Type extends MessageType<PropertyDefinition_Metadata> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.Metadata
 */
export declare const PropertyDefinition_Metadata: PropertyDefinition_Metadata$Type;
declare class PropertyDefinition_BoolSpec$Type extends MessageType<PropertyDefinition_BoolSpec> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.BoolSpec
 */
export declare const PropertyDefinition_BoolSpec: PropertyDefinition_BoolSpec$Type;
declare class PropertyDefinition_IntSpec$Type extends MessageType<PropertyDefinition_IntSpec> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.IntSpec
 */
export declare const PropertyDefinition_IntSpec: PropertyDefinition_IntSpec$Type;
declare class PropertyDefinition_EnumSpec$Type extends MessageType<PropertyDefinition_EnumSpec> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.PropertyDefinition.EnumSpec
 */
export declare const PropertyDefinition_EnumSpec: PropertyDefinition_EnumSpec$Type;
export {};
