// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "resolve.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "resolve.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
import { PropertyDefinition_Identifier } from "./property_definition";
/**
 * @generated from protobuf enum spotify.remote_config.ucs.proto.Fetch.Type
 */
export var Fetch_Type;
(function (Fetch_Type) {
    /**
     * @generated from protobuf enum value: BLOCKING = 0;
     */
    Fetch_Type[Fetch_Type["BLOCKING"] = 0] = "BLOCKING";
    /**
     * @generated from protobuf enum value: BACKGROUND_SYNC = 1;
     */
    Fetch_Type[Fetch_Type["BACKGROUND_SYNC"] = 1] = "BACKGROUND_SYNC";
    /**
     * @generated from protobuf enum value: ASYNC = 2;
     */
    Fetch_Type[Fetch_Type["ASYNC"] = 2] = "ASYNC";
    /**
     * @generated from protobuf enum value: PUSH_INITIATED = 3;
     */
    Fetch_Type[Fetch_Type["PUSH_INITIATED"] = 3] = "PUSH_INITIATED";
    /**
     * @generated from protobuf enum value: RECONNECT = 4;
     */
    Fetch_Type[Fetch_Type["RECONNECT"] = 4] = "RECONNECT";
})(Fetch_Type || (Fetch_Type = {}));
/**
 * @generated from protobuf enum spotify.remote_config.ucs.proto.DynamicContext.KnownContext
 */
export var DynamicContext_KnownContext;
(function (DynamicContext_KnownContext) {
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_INVALID = 0;
     */
    DynamicContext_KnownContext[DynamicContext_KnownContext["INVALID"] = 0] = "INVALID";
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_USER_ID = 1;
     */
    DynamicContext_KnownContext[DynamicContext_KnownContext["USER_ID"] = 1] = "USER_ID";
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_INSTALLATION_ID = 2;
     */
    DynamicContext_KnownContext[DynamicContext_KnownContext["INSTALLATION_ID"] = 2] = "INSTALLATION_ID";
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_VERSION = 3;
     */
    DynamicContext_KnownContext[DynamicContext_KnownContext["VERSION"] = 3] = "VERSION";
})(DynamicContext_KnownContext || (DynamicContext_KnownContext = {}));
// @generated message type with reflection information, may provide speed optimized methods
class ResolveRequest$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.ResolveRequest", [
            { no: 1, name: "property_set_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "fetch_type", kind: "message", T: () => Fetch },
            { no: 11, name: "context", kind: "message", T: () => Context },
            { no: 12, name: "backend_context", kind: "message", oneof: "resolutionContext", T: () => BackendContext }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.ResolveRequest
 */
export const ResolveRequest = new ResolveRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResolveResponse$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.ResolveResponse", [
            { no: 1, name: "configuration", kind: "message", T: () => Configuration }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.ResolveResponse
 */
export const ResolveResponse = new ResolveResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Configuration", [
            { no: 1, name: "configuration_assignment_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "fetch_time_millis", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 3, name: "assigned_values", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Configuration_AssignedValue }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration
 */
export const Configuration = new Configuration$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration_AssignedValue$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Configuration.AssignedValue", [
            { no: 1, name: "property_id", kind: "message", T: () => PropertyDefinition_Identifier },
            { no: 2, name: "metadata", kind: "message", T: () => Configuration_AssignedValue_Metadata },
            { no: 3, name: "bool_value", kind: "message", oneof: "structuredValue", T: () => Configuration_AssignedValue_BoolValue },
            { no: 4, name: "int_value", kind: "message", oneof: "structuredValue", T: () => Configuration_AssignedValue_IntValue },
            { no: 5, name: "enum_value", kind: "message", oneof: "structuredValue", T: () => Configuration_AssignedValue_EnumValue }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue
 */
export const Configuration_AssignedValue = new Configuration_AssignedValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration_AssignedValue_Metadata$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Configuration.AssignedValue.Metadata", [
            { no: 1, name: "policy_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "external_realm", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "external_realm_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.Metadata
 */
export const Configuration_AssignedValue_Metadata = new Configuration_AssignedValue_Metadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration_AssignedValue_BoolValue$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Configuration.AssignedValue.BoolValue", [
            { no: 1, name: "value", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.BoolValue
 */
export const Configuration_AssignedValue_BoolValue = new Configuration_AssignedValue_BoolValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration_AssignedValue_IntValue$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Configuration.AssignedValue.IntValue", [
            { no: 1, name: "value", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.IntValue
 */
export const Configuration_AssignedValue_IntValue = new Configuration_AssignedValue_IntValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration_AssignedValue_EnumValue$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Configuration.AssignedValue.EnumValue", [
            { no: 1, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.EnumValue
 */
export const Configuration_AssignedValue_EnumValue = new Configuration_AssignedValue_EnumValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Fetch$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Fetch", [
            { no: 1, name: "type", kind: "enum", T: () => ["spotify.remote_config.ucs.proto.Fetch.Type", Fetch_Type] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Fetch
 */
export const Fetch = new Fetch$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Context$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Context", [
            { no: 1, name: "context", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Context_ContextEntry }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Context
 */
export const Context = new Context$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Context_ContextEntry$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.Context.ContextEntry", [
            { no: 10, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 1, name: "known_context", kind: "enum", oneof: "context", T: () => ["spotify.remote_config.ucs.proto.DynamicContext.KnownContext", DynamicContext_KnownContext, "KNOWN_CONTEXT_"] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Context.ContextEntry
 */
export const Context_ContextEntry = new Context_ContextEntry$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BackendContext$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.BackendContext", [
            { no: 1, name: "system", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "service_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "static_context", kind: "message", T: () => BackendContext_StaticContext },
            { no: 4, name: "dynamic_context", kind: "message", T: () => DynamicContext },
            { no: 10, name: "surface_metadata", kind: "message", T: () => BackendContext_SurfaceMetadata }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.BackendContext
 */
export const BackendContext = new BackendContext$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BackendContext_StaticContext$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.BackendContext.StaticContext", [
            { no: 1, name: "system", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "service_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.BackendContext.StaticContext
 */
export const BackendContext_StaticContext = new BackendContext_StaticContext$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BackendContext_SurfaceMetadata$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.BackendContext.SurfaceMetadata", [
            { no: 1, name: "backend_sdk_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.BackendContext.SurfaceMetadata
 */
export const BackendContext_SurfaceMetadata = new BackendContext_SurfaceMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DynamicContext$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.DynamicContext", [
            { no: 1, name: "context_definition", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DynamicContext_ContextDefinition }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.DynamicContext
 */
export const DynamicContext = new DynamicContext$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DynamicContext_ContextDefinition$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.DynamicContext.ContextDefinition", [
            { no: 1, name: "known_context", kind: "enum", oneof: "context", T: () => ["spotify.remote_config.ucs.proto.DynamicContext.KnownContext", DynamicContext_KnownContext, "KNOWN_CONTEXT_"] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.DynamicContext.ContextDefinition
 */
export const DynamicContext_ContextDefinition = new DynamicContext_ContextDefinition$Type();
