// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "resolve.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
import { PropertyDefinition_Identifier } from "./property_definition";
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.ResolveRequest
 */
export interface ResolveRequest {
    /**
     * @generated from protobuf field: string property_set_id = 1;
     */
    propertySetId: string;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.Fetch fetch_type = 2;
     */
    fetchType?: Fetch;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.Context context = 11;
     */
    context?: Context;
    /**
     * @generated from protobuf oneof: resolution_context
     */
    resolutionContext: {
        oneofKind: "backendContext";
        /**
         * @deprecated
         * @generated from protobuf field: spotify.remote_config.ucs.proto.BackendContext backend_context = 12 [deprecated = true];
         */
        backendContext: BackendContext;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.ResolveResponse
 */
export interface ResolveResponse {
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.Configuration configuration = 1;
     */
    configuration?: Configuration;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Configuration
 */
export interface Configuration {
    /**
     * @generated from protobuf field: string configuration_assignment_id = 1;
     */
    configurationAssignmentId: string;
    /**
     * @generated from protobuf field: int64 fetch_time_millis = 2;
     */
    fetchTimeMillis: number;
    /**
     * @generated from protobuf field: repeated spotify.remote_config.ucs.proto.Configuration.AssignedValue assigned_values = 3;
     */
    assignedValues: Configuration_AssignedValue[];
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue
 */
export interface Configuration_AssignedValue {
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.PropertyDefinition.Identifier property_id = 1;
     */
    propertyId?: PropertyDefinition_Identifier;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.Configuration.AssignedValue.Metadata metadata = 2;
     */
    metadata?: Configuration_AssignedValue_Metadata;
    /**
     * @generated from protobuf oneof: structured_value
     */
    structuredValue: {
        oneofKind: "boolValue";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.Configuration.AssignedValue.BoolValue bool_value = 3;
         */
        boolValue: Configuration_AssignedValue_BoolValue;
    } | {
        oneofKind: "intValue";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.Configuration.AssignedValue.IntValue int_value = 4;
         */
        intValue: Configuration_AssignedValue_IntValue;
    } | {
        oneofKind: "enumValue";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.Configuration.AssignedValue.EnumValue enum_value = 5;
         */
        enumValue: Configuration_AssignedValue_EnumValue;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.Metadata
 */
export interface Configuration_AssignedValue_Metadata {
    /**
     * @generated from protobuf field: int64 policy_id = 1;
     */
    policyId: number;
    /**
     * @generated from protobuf field: string external_realm = 2;
     */
    externalRealm: string;
    /**
     * @generated from protobuf field: int64 external_realm_id = 3;
     */
    externalRealmId: number;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.BoolValue
 */
export interface Configuration_AssignedValue_BoolValue {
    /**
     * @generated from protobuf field: bool value = 1;
     */
    value: boolean;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.IntValue
 */
export interface Configuration_AssignedValue_IntValue {
    /**
     * @generated from protobuf field: int32 value = 1;
     */
    value: number;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.EnumValue
 */
export interface Configuration_AssignedValue_EnumValue {
    /**
     * @generated from protobuf field: string value = 1;
     */
    value: string;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Fetch
 */
export interface Fetch {
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.Fetch.Type type = 1;
     */
    type: Fetch_Type;
}
/**
 * @generated from protobuf enum spotify.remote_config.ucs.proto.Fetch.Type
 */
export declare enum Fetch_Type {
    /**
     * @generated from protobuf enum value: BLOCKING = 0;
     */
    BLOCKING = 0,
    /**
     * @generated from protobuf enum value: BACKGROUND_SYNC = 1;
     */
    BACKGROUND_SYNC = 1,
    /**
     * @generated from protobuf enum value: ASYNC = 2;
     */
    ASYNC = 2,
    /**
     * @generated from protobuf enum value: PUSH_INITIATED = 3;
     */
    PUSH_INITIATED = 3,
    /**
     * @generated from protobuf enum value: RECONNECT = 4;
     */
    RECONNECT = 4
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Context
 */
export interface Context {
    /**
     * @generated from protobuf field: repeated spotify.remote_config.ucs.proto.Context.ContextEntry context = 1;
     */
    context: Context_ContextEntry[];
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.Context.ContextEntry
 */
export interface Context_ContextEntry {
    /**
     * @generated from protobuf field: string value = 10;
     */
    value: string;
    /**
     * @generated from protobuf oneof: context
     */
    context: {
        oneofKind: "knownContext";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.DynamicContext.KnownContext known_context = 1;
         */
        knownContext: DynamicContext_KnownContext;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.BackendContext
 */
export interface BackendContext {
    /**
     * @deprecated
     * @generated from protobuf field: string system = 1 [deprecated = true];
     */
    system: string;
    /**
     * @deprecated
     * @generated from protobuf field: string service_name = 2 [deprecated = true];
     */
    serviceName: string;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.BackendContext.StaticContext static_context = 3;
     */
    staticContext?: BackendContext_StaticContext;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.DynamicContext dynamic_context = 4;
     */
    dynamicContext?: DynamicContext;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.BackendContext.SurfaceMetadata surface_metadata = 10;
     */
    surfaceMetadata?: BackendContext_SurfaceMetadata;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.BackendContext.StaticContext
 */
export interface BackendContext_StaticContext {
    /**
     * @generated from protobuf field: string system = 1;
     */
    system: string;
    /**
     * @generated from protobuf field: string service_name = 2;
     */
    serviceName: string;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.BackendContext.SurfaceMetadata
 */
export interface BackendContext_SurfaceMetadata {
    /**
     * @generated from protobuf field: string backend_sdk_version = 1;
     */
    backendSdkVersion: string;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.DynamicContext
 */
export interface DynamicContext {
    /**
     * @generated from protobuf field: repeated spotify.remote_config.ucs.proto.DynamicContext.ContextDefinition context_definition = 1;
     */
    contextDefinition: DynamicContext_ContextDefinition[];
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.DynamicContext.ContextDefinition
 */
export interface DynamicContext_ContextDefinition {
    /**
     * @generated from protobuf oneof: context
     */
    context: {
        oneofKind: "knownContext";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.DynamicContext.KnownContext known_context = 1;
         */
        knownContext: DynamicContext_KnownContext;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf enum spotify.remote_config.ucs.proto.DynamicContext.KnownContext
 */
export declare enum DynamicContext_KnownContext {
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_INVALID = 0;
     */
    INVALID = 0,
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_USER_ID = 1;
     */
    USER_ID = 1,
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_INSTALLATION_ID = 2;
     */
    INSTALLATION_ID = 2,
    /**
     * @generated from protobuf enum value: KNOWN_CONTEXT_VERSION = 3;
     */
    VERSION = 3
}
declare class ResolveRequest$Type extends MessageType<ResolveRequest> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.ResolveRequest
 */
export declare const ResolveRequest: ResolveRequest$Type;
declare class ResolveResponse$Type extends MessageType<ResolveResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.ResolveResponse
 */
export declare const ResolveResponse: ResolveResponse$Type;
declare class Configuration$Type extends MessageType<Configuration> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration
 */
export declare const Configuration: Configuration$Type;
declare class Configuration_AssignedValue$Type extends MessageType<Configuration_AssignedValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue
 */
export declare const Configuration_AssignedValue: Configuration_AssignedValue$Type;
declare class Configuration_AssignedValue_Metadata$Type extends MessageType<Configuration_AssignedValue_Metadata> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.Metadata
 */
export declare const Configuration_AssignedValue_Metadata: Configuration_AssignedValue_Metadata$Type;
declare class Configuration_AssignedValue_BoolValue$Type extends MessageType<Configuration_AssignedValue_BoolValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.BoolValue
 */
export declare const Configuration_AssignedValue_BoolValue: Configuration_AssignedValue_BoolValue$Type;
declare class Configuration_AssignedValue_IntValue$Type extends MessageType<Configuration_AssignedValue_IntValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.IntValue
 */
export declare const Configuration_AssignedValue_IntValue: Configuration_AssignedValue_IntValue$Type;
declare class Configuration_AssignedValue_EnumValue$Type extends MessageType<Configuration_AssignedValue_EnumValue> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Configuration.AssignedValue.EnumValue
 */
export declare const Configuration_AssignedValue_EnumValue: Configuration_AssignedValue_EnumValue$Type;
declare class Fetch$Type extends MessageType<Fetch> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Fetch
 */
export declare const Fetch: Fetch$Type;
declare class Context$Type extends MessageType<Context> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Context
 */
export declare const Context: Context$Type;
declare class Context_ContextEntry$Type extends MessageType<Context_ContextEntry> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.Context.ContextEntry
 */
export declare const Context_ContextEntry: Context_ContextEntry$Type;
declare class BackendContext$Type extends MessageType<BackendContext> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.BackendContext
 */
export declare const BackendContext: BackendContext$Type;
declare class BackendContext_StaticContext$Type extends MessageType<BackendContext_StaticContext> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.BackendContext.StaticContext
 */
export declare const BackendContext_StaticContext: BackendContext_StaticContext$Type;
declare class BackendContext_SurfaceMetadata$Type extends MessageType<BackendContext_SurfaceMetadata> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.BackendContext.SurfaceMetadata
 */
export declare const BackendContext_SurfaceMetadata: BackendContext_SurfaceMetadata$Type;
declare class DynamicContext$Type extends MessageType<DynamicContext> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.DynamicContext
 */
export declare const DynamicContext: DynamicContext$Type;
declare class DynamicContext_ContextDefinition$Type extends MessageType<DynamicContext_ContextDefinition> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.DynamicContext.ContextDefinition
 */
export declare const DynamicContext_ContextDefinition: DynamicContext_ContextDefinition$Type;
export {};
