// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,optimize_code_size
// @generated from protobuf file "Spotify.transcript-read-along.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://spclient.wg.spotify.com/transcript-read-along/v2/episode/
 *
 * @generated from protobuf message Transcript
 */
export interface Transcript {
    /**
     * @generated from protobuf field: string version = 1;
     */
    version: string;
    /**
     * @generated from protobuf field: string uri = 3;
     */
    uri: string;
    /**
     * @generated from protobuf field: string timeStamp = 4;
     */
    timeStamp: string;
    /**
     * @generated from protobuf field: repeated Section sections = 6;
     */
    sections: Section[];
}
/**
 * @generated from protobuf message Section
 */
export interface Section {
    /**
     * @generated from protobuf field: int32 startMs = 1;
     */
    startMs: number;
    /**
     * @generated from protobuf field: Content content = 3;
     */
    content?: Content;
    /**
     * @generated from protobuf field: Header header = 4;
     */
    header?: Header;
}
/**
 * @generated from protobuf message Content
 */
export interface Content {
    /**
     * @generated from protobuf field: Line line = 1;
     */
    line?: Line;
}
/**
 * @generated from protobuf message Line
 */
export interface Line {
    /**
     * @generated from protobuf field: int32 startMs = 1;
     */
    startMs: number;
    /**
     * @generated from protobuf field: string text = 2;
     */
    text: string;
}
/**
 * @generated from protobuf message Header
 */
export interface Header {
    /**
     * @generated from protobuf field: string texts = 1;
     */
    texts: string;
}
declare class Transcript$Type extends MessageType<Transcript> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Transcript
 */
export declare const Transcript: Transcript$Type;
declare class Section$Type extends MessageType<Section> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Section
 */
export declare const Section: Section$Type;
declare class Content$Type extends MessageType<Content> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Content
 */
export declare const Content: Content$Type;
declare class Line$Type extends MessageType<Line> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Line
 */
export declare const Line: Line$Type;
declare class Header$Type extends MessageType<Header> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Header
 */
export declare const Header: Header$Type;
export {};
