// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "ucs.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "ucs.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
import { AccountAttribute } from "./useraccount";
import { ResolveResponse } from "./resolve";
import { ResolveRequest } from "./resolve";
// @generated message type with reflection information, may provide speed optimized methods
class UcsRequest$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsRequest", [
            { no: 1, name: "caller_info", kind: "message", T: () => UcsRequest_CallerInfo },
            { no: 2, name: "resolve_request", kind: "message", T: () => ResolveRequest },
            { no: 3, name: "account_attributes_request", kind: "message", T: () => UcsRequest_AccountAttributesRequest }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsRequest
 */
export const UcsRequest = new UcsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UcsRequest_CallerInfo$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsRequest.CallerInfo", [
            { no: 1, name: "request_origin_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request_orgin_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsRequest.CallerInfo
 */
export const UcsRequest_CallerInfo = new UcsRequest_CallerInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UcsRequest_AccountAttributesRequest$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsRequest.AccountAttributesRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsRequest.AccountAttributesRequest
 */
export const UcsRequest_AccountAttributesRequest = new UcsRequest_AccountAttributesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UcsResponseWrapper$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsResponseWrapper", [
            { no: 1, name: "success", kind: "message", oneof: "result", T: () => UcsResponseWrapper_UcsResponse },
            { no: 2, name: "error", kind: "message", oneof: "result", T: () => UcsResponseWrapper_Error }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper
 */
export const UcsResponseWrapper = new UcsResponseWrapper$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UcsResponseWrapper_UcsResponse$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsResponseWrapper.UcsResponse", [
            { no: 5, name: "fetch_time_millis", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 1, name: "resolve_success", kind: "message", oneof: "resolveResult", T: () => ResolveResponse },
            { no: 2, name: "resolve_error", kind: "message", oneof: "resolveResult", T: () => UcsResponseWrapper_Error },
            { no: 3, name: "account_attributes_success", kind: "message", oneof: "accountAttributesResult", T: () => UcsResponseWrapper_AccountAttributesResponse },
            { no: 4, name: "account_attributes_error", kind: "message", oneof: "accountAttributesResult", T: () => UcsResponseWrapper_Error }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.UcsResponse
 */
export const UcsResponseWrapper_UcsResponse = new UcsResponseWrapper_UcsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UcsResponseWrapper_AccountAttributesResponse$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsResponseWrapper.AccountAttributesResponse", [
            { no: 1, name: "account_attributes", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => AccountAttribute } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.AccountAttributesResponse
 */
export const UcsResponseWrapper_AccountAttributesResponse = new UcsResponseWrapper_AccountAttributesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UcsResponseWrapper_Error$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.UcsResponseWrapper.Error", [
            { no: 1, name: "error_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "error_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "log_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.Error
 */
export const UcsResponseWrapper_Error = new UcsResponseWrapper_Error$Type();
