// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "ucs.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
import { AccountAttribute } from "./useraccount";
import { ResolveResponse } from "./resolve";
import { ResolveRequest } from "./resolve";
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsRequest
 */
export interface UcsRequest {
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsRequest.CallerInfo caller_info = 1;
     */
    callerInfo?: UcsRequest_CallerInfo;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.ResolveRequest resolve_request = 2;
     */
    resolveRequest?: ResolveRequest;
    /**
     * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsRequest.AccountAttributesRequest account_attributes_request = 3;
     */
    accountAttributesRequest?: UcsRequest_AccountAttributesRequest;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsRequest.CallerInfo
 */
export interface UcsRequest_CallerInfo {
    /**
     * @generated from protobuf field: string request_origin_id = 1;
     */
    requestOriginId: string;
    /**
     * @generated from protobuf field: string request_orgin_version = 2;
     */
    requestOrginVersion: string;
    /**
     * @generated from protobuf field: string reason = 3;
     */
    reason: string;
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsRequest.AccountAttributesRequest
 */
export interface UcsRequest_AccountAttributesRequest {
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper
 */
export interface UcsResponseWrapper {
    /**
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "success";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsResponseWrapper.UcsResponse success = 1;
         */
        success: UcsResponseWrapper_UcsResponse;
    } | {
        oneofKind: "error";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsResponseWrapper.Error error = 2;
         */
        error: UcsResponseWrapper_Error;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.UcsResponse
 */
export interface UcsResponseWrapper_UcsResponse {
    /**
     * @generated from protobuf field: int64 fetch_time_millis = 5;
     */
    fetchTimeMillis: number;
    /**
     * @generated from protobuf oneof: resolve_result
     */
    resolveResult: {
        oneofKind: "resolveSuccess";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.ResolveResponse resolve_success = 1;
         */
        resolveSuccess: ResolveResponse;
    } | {
        oneofKind: "resolveError";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsResponseWrapper.Error resolve_error = 2;
         */
        resolveError: UcsResponseWrapper_Error;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf oneof: account_attributes_result
     */
    accountAttributesResult: {
        oneofKind: "accountAttributesSuccess";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsResponseWrapper.AccountAttributesResponse account_attributes_success = 3;
         */
        accountAttributesSuccess: UcsResponseWrapper_AccountAttributesResponse;
    } | {
        oneofKind: "accountAttributesError";
        /**
         * @generated from protobuf field: spotify.remote_config.ucs.proto.UcsResponseWrapper.Error account_attributes_error = 4;
         */
        accountAttributesError: UcsResponseWrapper_Error;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.AccountAttributesResponse
 */
export interface UcsResponseWrapper_AccountAttributesResponse {
    /**
     * @generated from protobuf field: map<string, spotify.remote_config.ucs.proto.AccountAttribute> account_attributes = 1;
     */
    accountAttributes: {
        [key: string]: AccountAttribute;
    };
}
/**
 * @generated from protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.Error
 */
export interface UcsResponseWrapper_Error {
    /**
     * @generated from protobuf field: int32 error_code = 1;
     */
    errorCode: number;
    /**
     * @generated from protobuf field: string error_message = 2;
     */
    errorMessage: string;
    /**
     * @generated from protobuf field: optional string log_id = 3;
     */
    logId?: string;
}
declare class UcsRequest$Type extends MessageType<UcsRequest> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsRequest
 */
export declare const UcsRequest: UcsRequest$Type;
declare class UcsRequest_CallerInfo$Type extends MessageType<UcsRequest_CallerInfo> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsRequest.CallerInfo
 */
export declare const UcsRequest_CallerInfo: UcsRequest_CallerInfo$Type;
declare class UcsRequest_AccountAttributesRequest$Type extends MessageType<UcsRequest_AccountAttributesRequest> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsRequest.AccountAttributesRequest
 */
export declare const UcsRequest_AccountAttributesRequest: UcsRequest_AccountAttributesRequest$Type;
declare class UcsResponseWrapper$Type extends MessageType<UcsResponseWrapper> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper
 */
export declare const UcsResponseWrapper: UcsResponseWrapper$Type;
declare class UcsResponseWrapper_UcsResponse$Type extends MessageType<UcsResponseWrapper_UcsResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.UcsResponse
 */
export declare const UcsResponseWrapper_UcsResponse: UcsResponseWrapper_UcsResponse$Type;
declare class UcsResponseWrapper_AccountAttributesResponse$Type extends MessageType<UcsResponseWrapper_AccountAttributesResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.AccountAttributesResponse
 */
export declare const UcsResponseWrapper_AccountAttributesResponse: UcsResponseWrapper_AccountAttributesResponse$Type;
declare class UcsResponseWrapper_Error$Type extends MessageType<UcsResponseWrapper_Error> {
    constructor();
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.UcsResponseWrapper.Error
 */
export declare const UcsResponseWrapper_Error: UcsResponseWrapper_Error$Type;
export {};
