// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "useraccount.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "useraccount.proto" (package "spotify.remote_config.ucs.proto", syntax proto3)
// tslint:disable
//
// Extracted from: Spotify 1.1.61.583 (Windows)
//
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class AccountAttribute$Type extends MessageType {
    constructor() {
        super("spotify.remote_config.ucs.proto.AccountAttribute", [
            { no: 2, name: "bool_value", kind: "scalar", oneof: "value", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "long_value", kind: "scalar", oneof: "value", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 4, name: "string_value", kind: "scalar", oneof: "value", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.remote_config.ucs.proto.AccountAttribute
 */
export const AccountAttribute = new AccountAttribute$Type();
