// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "public/LyricsModel.proto" (package "com.spotify.lyrics.endpointretrofit.proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Represents color parameters for lyrics content view
 *
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.ColorData
 */
export interface ColorData {
    /**
     * View background color
     *
     * @generated from protobuf field: int32 background = 1;
     */
    background: number;
    /**
     * Text general color
     *
     * @generated from protobuf field: int32 text = 2;
     */
    text: number;
    /**
     * Currently playing lyrics text color
     *
     * @generated from protobuf field: int32 highlight_text = 3;
     */
    highlightText: number;
}
/**
 * Represents alternative lyrics variant
 *
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.Alternative
 */
export interface Alternative {
    /**
     * Lyrics language
     *
     * @generated from protobuf field: string language = 1;
     */
    language: string;
    /**
     * Lyrics lines
     *
     * @generated from protobuf field: repeated com.spotify.lyrics.endpointretrofit.proto.Line lines = 2;
     */
    lines: Line[];
    /**
     * Language type is Right-To-Left
     *
     * @generated from protobuf field: optional bool rtl_lang = 3;
     */
    rtlLang?: boolean;
}
/**
 * Represents a single lyrics line with timestamp, text info and syllables
 *
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.Line
 */
export interface Line {
    /**
     * Line start timestamp in millis during playback
     *
     * @generated from protobuf field: int64 start_time_ms = 1;
     */
    startTimeMs: number;
    /**
     * Line text info
     *
     * @generated from protobuf field: string text = 2;
     */
    text: string;
    /**
     * Line syllables
     *
     * @generated from protobuf field: repeated com.spotify.lyrics.endpointretrofit.proto.Syllable syllables = 3;
     */
    syllables: Syllable[];
}
/**
 * Represents syllable of the lyrics line
 *
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.Syllable
 */
export interface Syllable {
    /**
     * Syllable start timestamp in millis during playback
     *
     * @generated from protobuf field: int64 start_time_ms = 1;
     */
    startTimeMs: number;
    /**
     * Syllable chars count
     *
     * @generated from protobuf field: int64 num_chars = 2;
     */
    numChars: number;
}
/**
 * Lyrics content type
 *
 * @generated from protobuf enum com.spotify.lyrics.endpointretrofit.proto.SyncType
 */
export declare enum SyncType {
    /**
     * @generated from protobuf enum value: UNSYNCED = 0;
     */
    UNSYNCED = 0,
    /**
     * @generated from protobuf enum value: LINE_SYNCED = 1;
     */
    LINE_SYNCED = 1,
    /**
     * @generated from protobuf enum value: SYLLABLE_SYNCED = 2;
     */
    SYLLABLE_SYNCED = 2
}
declare class ColorData$Type extends MessageType<ColorData> {
    constructor();
    create(value?: PartialMessage<ColorData>): ColorData;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ColorData): ColorData;
    internalBinaryWrite(message: ColorData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.ColorData
 */
export declare const ColorData: ColorData$Type;
declare class Alternative$Type extends MessageType<Alternative> {
    constructor();
    create(value?: PartialMessage<Alternative>): Alternative;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Alternative): Alternative;
    internalBinaryWrite(message: Alternative, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.Alternative
 */
export declare const Alternative: Alternative$Type;
declare class Line$Type extends MessageType<Line> {
    constructor();
    create(value?: PartialMessage<Line>): Line;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Line): Line;
    internalBinaryWrite(message: Line, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.Line
 */
export declare const Line: Line$Type;
declare class Syllable$Type extends MessageType<Syllable> {
    constructor();
    create(value?: PartialMessage<Syllable>): Syllable;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Syllable): Syllable;
    internalBinaryWrite(message: Syllable, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.Syllable
 */
export declare const Syllable: Syllable$Type;
export {};
