// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,optimize_code_size
// @generated from protobuf file "Spotify.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://spclient.wg.spotify.com/color-lyrics/v2/track/
 *
 * @generated from protobuf message TrackReply
 */
export interface TrackReply {
    /**
     * @generated from protobuf field: Lyrics lyrics = 1;
     */
    lyrics?: Lyrics;
}
/**
 * @generated from protobuf message Lyrics
 */
export interface Lyrics {
    /**
     * SyncType syncType = 1;
     *
     * @generated from protobuf field: repeated Lines lines = 2;
     */
    lines: Lines[];
    /**
     * string providerLyricsId = 4;
     *
     * @generated from protobuf field: repeated Alternatives alternatives = 9;
     */
    alternatives: Alternatives[];
    /**
     * @generated from protobuf field: optional string language = 10;
     */
    language?: string;
}
/**
 * @generated from protobuf message Lines
 */
export interface Lines {
    /**
     * @generated from protobuf field: int32 startTimeMs = 1;
     */
    startTimeMs: number;
    /**
     * @generated from protobuf field: optional string words = 2;
     */
    words?: string;
}
/**
 * @generated from protobuf message Alternatives
 */
export interface Alternatives {
    /**
     * @generated from protobuf field: string language = 1;
     */
    language: string;
    /**
     * @generated from protobuf field: repeated string lines = 2 [packed = false];
     */
    lines: string[];
}
declare class TrackReply$Type extends MessageType<TrackReply> {
    constructor();
}
/**
 * @generated MessageType for protobuf message TrackReply
 */
export declare const TrackReply: TrackReply$Type;
declare class Lyrics$Type extends MessageType<Lyrics> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Lyrics
 */
export declare const Lyrics: Lyrics$Type;
declare class Lines$Type extends MessageType<Lines> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Lines
 */
export declare const Lines: Lines$Type;
declare class Alternatives$Type extends MessageType<Alternatives> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Alternatives
 */
export declare const Alternatives: Alternatives$Type;
export {};
