// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,optimize_code_size
// @generated from protobuf file "Spotify.transcript.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://episode-transcripts.spotifycdn.com/1.0/spotify:transcript:
 *
 * @generated from protobuf message Transcript
 */
export interface Transcript {
    /**
     * @generated from protobuf field: string version = 1;
     */
    version: string;
    /**
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
    /**
     * @generated from protobuf field: string timeStamp = 3;
     */
    timeStamp: string;
    /**
     * @generated from protobuf field: repeated Section sections = 4;
     */
    sections: Section[];
}
/**
 * @generated from protobuf message Section
 */
export interface Section {
    /**
     * @generated from protobuf field: int32 startMs = 2;
     */
    startMs: number;
    /**
     * @generated from protobuf field: Content content = 3;
     */
    content?: Content;
}
/**
 * @generated from protobuf message Content
 */
export interface Content {
    /**
     * @generated from protobuf field: repeated string texts = 1;
     */
    texts: string[];
}
declare class Transcript$Type extends MessageType<Transcript> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Transcript
 */
export declare const Transcript: Transcript$Type;
declare class Section$Type extends MessageType<Section> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Section
 */
export declare const Section: Section$Type;
declare class Content$Type extends MessageType<Content> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Content
 */
export declare const Content: Content$Type;
export {};
