// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,generate_dependencies
// @generated from protobuf file "Spotify.ColorLyricsResponse.proto" (package "com.spotify.lyrics.endpointretrofit.proto", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://spclient.wg.spotify.com/color-lyrics/v2/track/
 *
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.ColorLyricsResponse
 */
export interface ColorLyricsResponse {
    /**
     * @generated from protobuf field: com.spotify.lyrics.endpointretrofit.proto.LyricsResponse lyrics = 1;
     */
    lyrics?: LyricsResponse;
    /**
     * @generated from protobuf field: optional com.spotify.lyrics.endpointretrofit.proto.ColorData colors = 2;
     */
    colors?: ColorData;
    /**
     * @generated from protobuf field: optional bool has_vocal_removal = 3;
     */
    hasVocalRemoval?: boolean;
    /**
     * @generated from protobuf field: optional com.spotify.lyrics.endpointretrofit.proto.ColorData vocal_removal_colors = 4;
     */
    vocalRemovalColors?: ColorData;
}
/**
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.LyricsResponse
 */
export interface LyricsResponse {
    /**
     * @generated from protobuf field: com.spotify.lyrics.endpointretrofit.proto.SyncType sync_type = 1;
     */
    syncType: SyncType;
    /**
     * @generated from protobuf field: repeated com.spotify.lyrics.endpointretrofit.proto.LyricsLine lines = 2;
     */
    lines: LyricsLine[];
    /**
     * @generated from protobuf field: string provider = 3;
     */
    provider: string;
    /**
     * @generated from protobuf field: string provider_lyrics_id = 4;
     */
    providerLyricsId: string;
    /**
     * @generated from protobuf field: string provider_display_name = 5;
     */
    providerDisplayName: string;
    /**
     * @generated from protobuf field: optional com.spotify.lyrics.endpointretrofit.proto.AndroidIntent sync_lyrics_android_intent = 6;
     */
    syncLyricsAndroidIntent?: AndroidIntent;
    /**
     * @generated from protobuf field: string sync_lyrics_uri = 7;
     */
    syncLyricsUri: string;
    /**
     * @generated from protobuf field: bool is_dense_typeface = 8;
     */
    isDenseTypeface: boolean;
    /**
     * @generated from protobuf field: repeated com.spotify.lyrics.endpointretrofit.proto.Alternative alternatives = 9;
     */
    alternatives: Alternative[];
    /**
     * @generated from protobuf field: string lang = 10;
     */
    lang: string;
    /**
     * @generated from protobuf field: optional bool rtl_lang = 11;
     */
    rtlLang?: boolean;
    /**
     * @generated from protobuf field: optional bool show_upsell = 13;
     */
    showUpsell?: boolean;
}
/**
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.LyricsLine
 */
export interface LyricsLine {
    /**
     * @generated from protobuf field: int64 start_time_ms = 1;
     */
    startTimeMs: string;
    /**
     * @generated from protobuf field: optional string text = 2;
     */
    text?: string;
    /**
     * @generated from protobuf field: repeated com.spotify.lyrics.endpointretrofit.proto.Syllable syllables = 3;
     */
    syllables: Syllable[];
}
/**
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.Syllable
 */
export interface Syllable {
    /**
     * @generated from protobuf field: int64 start_time_ms = 1;
     */
    startTimeMs: string;
    /**
     * @generated from protobuf field: int64 num_chars = 2;
     */
    numChars: string;
}
/**
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.ColorData
 */
export interface ColorData {
    /**
     * @generated from protobuf field: int32 background = 1;
     */
    background: number;
    /**
     * @generated from protobuf field: int32 text = 2;
     */
    text: number;
    /**
     * @generated from protobuf field: int32 highlight_text = 3;
     */
    highlightText: number;
}
/**
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.AndroidIntent
 */
export interface AndroidIntent {
    /**
     * @generated from protobuf field: string provider = 1;
     */
    provider: string;
    /**
     * @generated from protobuf field: string provider_android_app_id = 2;
     */
    providerAndroidAppId: string;
    /**
     * @generated from protobuf field: string action = 3;
     */
    action: string;
    /**
     * @generated from protobuf field: string data = 4;
     */
    data: string;
    /**
     * @generated from protobuf field: string content_type = 5;
     */
    contentType: string;
}
/**
 * @generated from protobuf message com.spotify.lyrics.endpointretrofit.proto.Alternative
 */
export interface Alternative {
    /**
     * @generated from protobuf field: string language = 1;
     */
    language: string;
    /**
     * @generated from protobuf field: repeated string lines = 2 [packed = false];
     */
    lines: string[];
}
/**
 * @generated from protobuf enum com.spotify.lyrics.endpointretrofit.proto.SyncType
 */
export declare enum SyncType {
    /**
     * @generated from protobuf enum value: UNSYNCED = 0;
     */
    UNSYNCED = 0,
    /**
     * @generated from protobuf enum value: LINE_SYNCED = 1;
     */
    LINE_SYNCED = 1,
    /**
     * @generated from protobuf enum value: SYLLABLE_SYNCED = 2;
     */
    SYLLABLE_SYNCED = 2
}
declare class ColorLyricsResponse$Type extends MessageType<ColorLyricsResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.ColorLyricsResponse
 */
export declare const ColorLyricsResponse: ColorLyricsResponse$Type;
declare class LyricsResponse$Type extends MessageType<LyricsResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.LyricsResponse
 */
export declare const LyricsResponse: LyricsResponse$Type;
declare class LyricsLine$Type extends MessageType<LyricsLine> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.LyricsLine
 */
export declare const LyricsLine: LyricsLine$Type;
declare class Syllable$Type extends MessageType<Syllable> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.Syllable
 */
export declare const Syllable: Syllable$Type;
declare class ColorData$Type extends MessageType<ColorData> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.ColorData
 */
export declare const ColorData: ColorData$Type;
declare class AndroidIntent$Type extends MessageType<AndroidIntent> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.AndroidIntent
 */
export declare const AndroidIntent: AndroidIntent$Type;
declare class Alternative$Type extends MessageType<Alternative> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.spotify.lyrics.endpointretrofit.proto.Alternative
 */
export declare const Alternative: Alternative$Type;
export {};
