// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,generate_dependencies
// @generated from protobuf file "Spotify.ColorLyricsResponse.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://spclient.wg.spotify.com/color-lyrics/v2/track/
 *
 * @generated from protobuf message ColorLyricsResponse
 */
export interface ColorLyricsResponse {
    /**
     * @generated from protobuf field: LyricsResponse lyrics = 1;
     */
    lyrics?: LyricsResponse;
    /**
     * @generated from protobuf field: optional ColorData colors = 2;
     */
    colors?: ColorData;
    /**
     * @generated from protobuf field: optional bool hasVocalRemoval = 3;
     */
    hasVocalRemoval?: boolean;
    /**
     * @generated from protobuf field: optional ColorData vocalRemovalColors = 4;
     */
    vocalRemovalColors?: ColorData;
}
/**
 * @generated from protobuf message LyricsResponse
 */
export interface LyricsResponse {
    /**
     * @generated from protobuf field: SyncType syncType = 1;
     */
    syncType: SyncType;
    /**
     * @generated from protobuf field: repeated LyricsLine lines = 2;
     */
    lines: LyricsLine[];
    /**
     * @generated from protobuf field: string provider = 3;
     */
    provider: string;
    /**
     * @generated from protobuf field: string providerLyricsId = 4;
     */
    providerLyricsId: string;
    /**
     * @generated from protobuf field: string providerDisplayName = 5;
     */
    providerDisplayName: string;
    /**
     * @generated from protobuf field: optional AndroidIntent syncLyricsAndroidIntent = 6;
     */
    syncLyricsAndroidIntent?: AndroidIntent;
    /**
     * @generated from protobuf field: string syncLyricsUri = 7;
     */
    syncLyricsUri: string;
    /**
     * @generated from protobuf field: bool isDenseTypeface = 8;
     */
    isDenseTypeface: boolean;
    /**
     * @generated from protobuf field: repeated Alternative alternatives = 9;
     */
    alternatives: Alternative[];
    /**
     * @generated from protobuf field: string language = 10;
     */
    language: string;
    /**
     * @generated from protobuf field: optional bool isRtlLanguage = 11;
     */
    isRtlLanguage?: boolean;
    /**
     * @generated from protobuf field: int32 fullscreenAction = 12;
     */
    fullscreenAction: number;
    /**
     * @generated from protobuf field: optional bool showUpsell = 13;
     */
    showUpsell?: boolean;
}
/**
 * @generated from protobuf message LyricsLine
 */
export interface LyricsLine {
    /**
     * @generated from protobuf field: int64 startTimeMs = 1;
     */
    startTimeMs: string;
    /**
     * @generated from protobuf field: optional string words = 2;
     */
    words?: string;
    /**
     * @generated from protobuf field: repeated Syllable syllables = 3;
     */
    syllables: Syllable[];
    /**
     * @generated from protobuf field: optional int64 endTimeMs = 4;
     */
    endTimeMs?: string;
}
/**
 * @generated from protobuf message Syllable
 */
export interface Syllable {
    /**
     * @generated from protobuf field: int64 startTimeMs = 1;
     */
    startTimeMs: string;
    /**
     * @generated from protobuf field: int64 numChars = 2;
     */
    numChars: string;
}
/**
 * @generated from protobuf message ColorData
 */
export interface ColorData {
    /**
     * @generated from protobuf field: int32 background = 1;
     */
    background: number;
    /**
     * @generated from protobuf field: int32 text = 2;
     */
    text: number;
    /**
     * @generated from protobuf field: int32 highlightText = 3;
     */
    highlightText: number;
}
/**
 * @generated from protobuf message AndroidIntent
 */
export interface AndroidIntent {
    /**
     * @generated from protobuf field: string provider = 1;
     */
    provider: string;
    /**
     * @generated from protobuf field: string providerAndroidAppId = 2;
     */
    providerAndroidAppId: string;
    /**
     * @generated from protobuf field: string action = 3;
     */
    action: string;
    /**
     * @generated from protobuf field: string data = 4;
     */
    data: string;
    /**
     * @generated from protobuf field: string contentType = 5;
     */
    contentType: string;
}
/**
 * @generated from protobuf message Alternative
 */
export interface Alternative {
    /**
     * @generated from protobuf field: string language = 1;
     */
    language: string;
    /**
     * @generated from protobuf field: repeated string lines = 2 [packed = false];
     */
    lines: string[];
}
/**
 * @generated from protobuf enum SyncType
 */
export declare enum SyncType {
    /**
     * @generated from protobuf enum value: UNSYNCED = 0;
     */
    UNSYNCED = 0,
    /**
     * @generated from protobuf enum value: LINE_SYNCED = 1;
     */
    LINE_SYNCED = 1,
    /**
     * @generated from protobuf enum value: SYLLABLE_SYNCED = 2;
     */
    SYLLABLE_SYNCED = 2
}
declare class ColorLyricsResponse$Type extends MessageType<ColorLyricsResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message ColorLyricsResponse
 */
export declare const ColorLyricsResponse: ColorLyricsResponse$Type;
declare class LyricsResponse$Type extends MessageType<LyricsResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message LyricsResponse
 */
export declare const LyricsResponse: LyricsResponse$Type;
declare class LyricsLine$Type extends MessageType<LyricsLine> {
    constructor();
}
/**
 * @generated MessageType for protobuf message LyricsLine
 */
export declare const LyricsLine: LyricsLine$Type;
declare class Syllable$Type extends MessageType<Syllable> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Syllable
 */
export declare const Syllable: Syllable$Type;
declare class ColorData$Type extends MessageType<ColorData> {
    constructor();
}
/**
 * @generated MessageType for protobuf message ColorData
 */
export declare const ColorData: ColorData$Type;
declare class AndroidIntent$Type extends MessageType<AndroidIntent> {
    constructor();
}
/**
 * @generated MessageType for protobuf message AndroidIntent
 */
export declare const AndroidIntent: AndroidIntent$Type;
declare class Alternative$Type extends MessageType<Alternative> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Alternative
 */
export declare const Alternative: Alternative$Type;
export {};
